 
services:
  # iris:
  #   build:
  #     context: ./iris
  #     dockerfile: Dockerfile
  #     target: final
  #   restart: always
  #   command: --check-caps false --ISCAgent false
  #   ports:
  #     - 1972
  #     - 52773
  #     - 53773
  #   volumes:
  #     - ./iris:/home/irisowner/dev
  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - 8889:8888
    volumes:
      - type: bind
        source: myapp
        target: /home/jovyan/workspace
    command: start-notebook.py --NotebookApp.token=''
    # depends_on: ['iris']

volumes:
  myapp:


